services:
  - type: web
    plan: free
    name: expense-tracker-web
    runtime: python
    buildCommand: "pip install -r requirements.txt && python expense_tracker/manage.py migrate"
    startCommand: "gunicorn expense_tracker.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
